### ISSUE TITLE
caasp-kvm re-downloads images on every run.

### ISSUE THREAD

**Issue by bear454** [kubic-project/automation#143]
https://github.com/kubic-project/automation/blob/master/caasp-kvm/caasp-kvm#L101

Some mechanism should be present to reuse existing downloads, instead of requiring a fresh download for every run... with download times in the hours over VPN, debugging is an infuriating process.

**Comment by kiall** [comment]
You can supply a `--image file://<path>` flag to the caasp-kvm tool to have it use a pre-downloaded image. The latest downloaded image will be available in the downloads folder as "kvm-<channel>" - i.e. `downloads/kvm-devel` - right now tho, a fully qualified path needs to be supplied. We should really update this to take a name relative to either the downloads dir, or `pwd` for ease though.

This only works for the KVM image, the smaller velum docker image will still be downloaded even with that flag, while that's clearly still an issue, it's been a small enough issue that we haven't fixed it yet!
