### ISSUE TITLE
OpenStack Heat: Non-admin nodes have iptables rules that block DNS queries

### ISSUE THREAD

**Issue by BlaineEXE** [kubic-project/automation#210]
I use the Heat tooling to setup a 1-master, 4-minion cluster.

All nodes talk to the same dnsmasq, but only the admin node's packets arrive at the DNS server (`172.24.0.2`). The packets from all of the other nodes (masters and minions) never reach the DNS server.

Flushing the iptables rules on the master/minions and adding back rules to allow all traffic allows the nodes' packets to reach the DNS server again.

My current workaround is to set the `dns_nameserver` heat parameter to the suse.de DNS IP `10.160.0.1`. If I use the default value of `172.24.0.2`, I see the above behavior where only the admin can resolve via DNS.

**Comment by BlaineEXE** [comment]
@kiall, do you have any thoughts as to whether this is an issue with something in automation or whether it's something in CaaSP itself?

**Comment by BlaineEXE** [comment]
This also affects the masters' and minions' ability to sync to the admin's NTP server. NTP servers from 0.opensuse.pool.ntp.org are accepted, but the admin server is not.

**Comment by kiall** [comment]
I'm not sure I understand, what iptables rules? I don't think I've ever seen these before?

**Comment by BlaineEXE** [comment]
I don't know why it is happening. When I stand up a cluster with Heat, I cannot use 172.24.0.2 (created in openstack) for my DNS server, because the master and minion's firewalls block the traffic from reaching the DNS server. The requests from everything but the admin node never reach 172.24.0.2.

If I wipe all iptables rules and replace them with rules to enable all traffic, the nodes are able to reach the DNS again.

I have further found recently that the iptables rules on master and minions also block NTP traffic intended for the admin node.

I'm not sure why I'm seeing these issues. I can work around the DNS issue by using '8.8.8.8' instead as the DNS server, and I can workaround the NTP issue by using '0.opensuse.pool.ntp.org' as the NTP server. I'm not sure why I'm getting the issues in the first place, however. The workarounds work but aren't ideal.

**Comment by BlaineEXE** [comment]
Issue was with conflicting cluster network address.
