### ISSUE TITLE
caasp-kvm deploy is instable

### ISSUE THREAD

**Issue by MalloZup** [kubic-project/automation#367]
### description
just using  ``` ./caasp-devenv --build -m 1 -w 2 --bootstrap --testinfra``` with  a opensuse42.3 leap OS.

The deploy on terraform fails on several issues/race-conditions..

From 5/10 times i get this failures.

### how to reproduce issues

- [ ] race condition on retriving various resources

```bash
Error: Error refreshing state: 2 error(s) occurred:

* libvirt_cloudinit.admin: 1 error(s) occurred:

* libvirt_cloudinit.admin: libvirt_cloudinit.admin: error while retrieving remote ISO: Can't retrieve volume /var/images/admin_cloud_init.iso
* libvirt_volume.img: 1 error(s) occurred:

* libvirt_volume.img: libvirt_volume.img: can't retrieve volume /var/images/devel

```

Problems could be:
- It might be that  the cluster.tf file (the file generated via erb) is not assuming the right dependencies.
We could add via HCLn language dep to wait for resources.
- terraform-libvirt-plugin

**Comment by MalloZup** [comment]
@inercia  just looking at the tf file i don't think the issue is on HCL language solvable.

From my pov we have a race condition on the cloud-init resource on terraform libvirt plugin.

**Comment by inercia** [comment]
This is an internal bug in the Terraform libvirt provider. I think it was something like, when the volume is created, it is not removed on the event of a failure, so the next time you will find the volume being referenced in the state file, but not phisically present in the pool...

**Comment by MalloZup** [comment]
i'm closing this in favor for libvirt-plugin issue
