### ISSUE TITLE
caasp-kvm without cluster nodes is broken

### ISSUE THREAD

**Issue by bear454** [kubic-project/automation#427]
`./caasp-kvm --build -m 0 -w 0` fails with the following error:

```
Error: Error refreshing state: 2 error(s) occurred:
 
* output.masters: At column 56, line 1: list "libvirt_domain.master.*.network_interface.0.addresses" does not have any elements so cannot determine type. in:
 
${libvirt_domain.master.*.network_interface.0.addresses[0]}
* output.workers: At column 56, line 1: list "libvirt_domain.worker.*.network_interface.0.addresses" does not have any elements so cannot determine type. in:
 
${libvirt_domain.worker.*.network_interface.0.addresses[0]}
```

This _used to_ work; I believe the error was introduced as an unintended byproduct of https://github.com/kubic-project/automation/commit/7d17c4e79050309995f9725261c16fec1119ae36 .

**Comment by MalloZup** [comment]
yop i think best solution would to introduce a bash check that would check the `m` and `-w` variable are not zero and prompt that you need at least 1 master and 1 worker.

Afaik there is no use-cases for this

**Comment by bear454** [comment]
The use case is development on just the administrative node, some examples are:

* Debugging cluster initialization
* Development on Velum
* Situations where the worker nodes are deployed through alternative means (e.g. `salt-cloud`)

**Comment by stefsuse** [comment]
Since this was last updated the scripts have been updated to default to 1 master and 2 workers, which is defined in the official documentation as a minimal viable cluster, due to etcd considerations. Closing this.
