### ISSUE TITLE
caasp-kvm: not enough memory for Admin node

### ISSUE THREAD

**Issue by bear454** [kubic-project/automation#429]
CaaSP documentation states
> Minimal amount of RAM: 8 GB
-- https://www.suse.com/releasenotes/x86_64/SUSE-CAASP/2.0/#Intro.Requirement.System

... but caasp-kvm launches the admin node with 4GB of RAM by default; as a result MySQL falls over "out of memory" on a regular basis.

**Comment by MalloZup** [comment]
ok we might add more ram on that :+1:

**Comment by kiall** [comment]
In CI, we do use caasp-kvm - and we already bump it up to 8GB. The biggest issue with bumping the default is, many developers don't have the RAM available to do that! For simple development environments, 4GB seems to work - so long as you're not working on Velum and running the Velum tests etc.

If you're spending most of your time working on Velum/running the Velum tests - you can put something like this in your ~/.bashrc:

    export CAASP_ADMIN_RAM=8192

or provide the `--admin-ram 8192` flag when building.

**Comment by MalloZup** [comment]
@bear454  i think than we can close this is issue.  What do you think?
We might adding some troubleshooting doc but imho in this case is not neccessary afaik.
