### ISSUE TITLE
caasp-kvm not bulding kvm

### ISSUE THREAD

**Issue by cosmo83** [kubic-project/automation#455]
Iam trying to run caasp-kvm

Its not building the velum packages and getting struck. I even tried to increase the RAM on the admin node and eve tried the latest kubic build.

Can someone help me understand what am i doing wrong ?

admin:~ # docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS               NAMES
5783c3b7d6bc        71b8fd9eb857        "/setup-mysql.sh"        9 minutes ago       Up 9 minutes                            k8s_mariadb-user-secrets_velum-public-127.0.0.1_default_074ed0e5ce1409892de075fd40d1c423_0
279b9ca649c3        kubic/pause:0.1     "/usr/share/suse-d..."   10 minutes ago      Up 9 minutes                            k8s_POD_velum-public-127.0.0.1_default_074ed0e5ce1409892de075fd40d1c423_0
36ffc4c1f2cd        kubic/pause:0.1     "/usr/share/suse-d..."   11 minutes ago      Up 9 minutes                            k8s_POD_velum-private-127.0.0.1_default_1a66432d6c90fa99a70a8731e06b736d_0
a53cffed6472        kubic/pause:0.1     "/usr/share/suse-d..."   11 minutes ago      Up 10 minutes                           k8s_POD_haproxy-127.0.0.1_kube-system_e4941225b9214d87b2e671ada82ad940_0

**Comment by MalloZup** [comment]
@cosmo83  hi! i think is because you don't have the tunnel.

Can you try this branch @cosmo83  https://github.com/kubic-project/automation/pull/524

**Comment by suseclee** [comment]
I tried on someday on last Thursday or Wednesday, caasp-kvm was built and deployed as usual. But Friday evening (PST), it failed with 2 errors.

1. waiting too much for 
    User selects minion roles
     >>> Wait until orchestration is complete (Timeout: 3600)
2. after the long wating, I had
<<< Orchestration completed
>>> Checking if orchestration succeeded
  User bootstraps the cluster (FAILED - 1)

Failures:

  1) Boostrap cluster User bootstraps the cluster
     Failure/Error: expect(page).to have_css(".fa-check-circle-o", count: node_number, wait: 5)
       expected to find css ".fa-check-circle-o" 3 times but there were no matches
     # ./spec/features/02-bootstrap-cluster.rb:144:in `block (4 levels) in <top (required)>'
     # ./.bundler/ruby/2.5.0/gems/capybara-2.14.4/lib/capybara/session.rb:327:in `within'
     # ./.bundler/ruby/2.5.0/gems/capybara-2.14.4/lib/capybara/dsl.rb:50:in `block (2 levels) in <module:DSL>'
     # ./.bundler/ruby/2.5.0/gems/capybara-2.14.4/lib/capybara/rspec/matcher_proxies.rb:14:in `within'
     # ./spec/features/02-bootstrap-cluster.rb:143:in `block (3 levels) in <top (required)>'
     # ./spec/support/helpers.rb:6:in `with_screenshot'
     # ./spec/features/02-bootstrap-cluster.rb:142:in `block (2 levels) in <top (required)>'
     # ./spec/spec_helper.rb:142:in `block (3 levels) in <top (required)>'
     # ./spec/spec_helper.rb:142:in `block (2 levels) in <top (required)>'

Finished in 47 minutes 29 seconds (files took 0.36766 seconds to load)
7 examples, 1 failure

Failed examples:

rspec ./spec/features/02-bootstrap-cluster.rb:113 # Boostrap cluster User bootstraps the cluster
  

Is it same symptom?

**Comment by stefsuse** [comment]
this looks like an attempt at running kubic, though scripts for that live in another repository. Closing
