### ISSUE TITLE
caasp-kvm --destroy requires internal SUSE access

### ISSUE THREAD

**Issue by bear454** [kubic-project/automation#482]
```
~/kubic-project/automation/caasp-kvm> ./caasp-kvm --destroy
ping: unknown host download.suse.de
Internal network not reachable!
  use ./caasp-kvm --image channel://kubic
```
Destroy operation should not require any access beyond the machine it's running on.

**Comment by MalloZup** [comment]
fixed by https://github.com/kubic-project/automation/pull/524

**Comment by bear454** [comment]
![happy dance](https://media.giphy.com/media/14qb1Uhf40ndw4/giphy.gif)
