### ISSUE TITLE
CI ISSUE: pipeline Flakyness on building docker Env.

### ISSUE THREAD

**Issue by MalloZup** [kubic-project/automation#534]
http://jenkins.caasp.suse.net/blue/organizations/jenkins/automation.integration/detail/PR-529/10/pipeline

```bash
libvirt_domain.admin (remote-exec): 

libvirt_domain.admin (remote-exec): failed to write digest data: sync /var/lib/docker/image/btrfs/imagedb/content/sha256/.tmp-6f367563d8a7ab484aa4679b8c6e0bb1ca641f652a911ed884d9b64beaccf4f5207165652: input/output error


Error: Error applying plan:


1 error(s) occurred:


* libvirt_domain.admin: error executing "/tmp/terraform_1962860862.sh": Process exited with status 1


Terraform does not automatically rollback in the face of errors.

```

@MaximilianMeister  did you saw something like this yesterday?

**Comment by stefsuse** [comment]
Retries are certainly reasonable for large orchestrations like this, but I would not expect to see this error often. The orchestrator should also detect what the error is and only retry on transient errors, such as HTTP 500s. I restarted the build anyway, let's see if it fails same place.

**Comment by stefsuse** [comment]
Closing this as this was definitely random corruption after some investigation. A PR has since been accepted that logs more information for the next time this happens.
