### ISSUE TITLE
Wrong bundler version

### ISSUE THREAD

**Issue by tdaines42** [kubic-project/automation#577]
A recent update to Bundler seems to be causing the install to fail in the velum devel container.

This results in the following error while the caasp velum devel image is being built:
```
ERROR:  Error installing bundler:
bundler requires Ruby version >= 2.3.0
```
Most likely this line `gem install --no-ri --no-rdoc bundler -n /usr/bin && \` in `caasp-kvm/tools/build-velum-image::build_fresh_image()` needs to be updated to something like `gem install --no-ri --no-rdoc bundler -n /usr/bin -v 1.17.3 && \`. 

I tested this manually and the image seemed to build just fine.

**Comment by suseclee** [comment]
Ty. This is very good analogy and exact solution. This shows how a simple upstream change can end up with building failure.

**Comment by stefsuse** [comment]
Closing now that backport is done.
