### ISSUE TITLE
This repo is not relevant to Kubic - can we rename/make clear in README

### ISSUE THREAD

**Issue by sysrich** [kubic-project/automation#585]
Kubic, and none of the official, or even unofficial, Kubic assets (eg. those on https://software.opensuse.org or https://download.opensuse.org/tumbleweed) support the use of this repo

and yet repeatedly community members complain when they try to use this and find it doesn't work

I understand and respect the history so I'm not proposing we remove this repo from the kubic-project github, but given it isn't relevant to the kubic-project and its future, can we rename it to something like "CaaSP-automation"?

Or at least record in the README that the Kubic Project does not use this repo and it is not relevant to any of the available openSUSE Kubic media, ISOs, VM images, or containers?

**Comment by stefsuse** [comment]
Makes sense to me, and thanks for clarifying, I wondered about a handful of scripts myself. 

If you issue a PR for the README suggestion I'll approve and merge. Renaming the repo will require changes in CI etc so we would have to look into that another time.

**Comment by sysrich** [comment]
@stefsuse PR sent, thanks :)
