### ISSUE TITLE
This can't be used with Kubic? What's the point?!

### ISSUE THREAD

**Issue by Conan-Kudo** [kubic-project/automation#637]
> **NOTE: The tools in this repo should not be used on openSUSE Kubic**

What is the _point_ of this repo being part of Kubic if you can't even use it with Kubic? 💢 

This was noted in #585 and a PR to add this note was accepted in #586, but the correct answer here would have been to move it to some dark corner of the interwebs where broken projects are left to rot.

More seriously, if there's going to be CaaSP-specific tools, they need to be in their own place, instead of being part of Kubic and confusing people. Or just kill it and start using the Kubic stuff with CaaSP too, I'm okay with that. 😉

**Comment by hwoarang** [comment]
Yes we will move them
